
#PRIMERO DEBEMOS SETEAR EL AUTOCOMMINT PARA QUE PODAMOS REALIZAR LAS TRANSACTION#
select @@autocommit;
set  @@autocommit=0;

#SE COMIENZA UNA TRANSACION CON VARIOS INSERT A LA TABLA ARTICULOS , SE APLICA SAVEPOINT POR LOTE, CON EL FIN DE PODER  TENER CONTROLADO LOS INSERT MASIVOS Y PODER REALIZAR ROLLBACK POR SAVEPOINT #
START TRANSACTION;
INSERT INTO ARTICULOS (NOMBRE,CODIGO,PRECIO_UNITARIO,ID_PROVEEDOR,PRECIO_COMPRA) VALUES ('FICHA ELECTRICA6','0255546FE',70,4,10);
INSERT INTO ARTICULOS (NOMBRE,CODIGO,PRECIO_UNITARIO,ID_PROVEEDOR,PRECIO_COMPRA) VALUES ('FICHA ELECTRICA2','0255565FE',80,4,20);
INSERT INTO ARTICULOS (NOMBRE,CODIGO,PRECIO_UNITARIO,ID_PROVEEDOR,PRECIO_COMPRA) VALUES ('FICHA ELECTRICA3','0255875FE',90,4,30);
INSERT INTO ARTICULOS (NOMBRE,CODIGO,PRECIO_UNITARIO,ID_PROVEEDOR,PRECIO_COMPRA) VALUES ('FICHA ELECTRICA4','0255125FE',100,4,40);
INSERT INTO ARTICULOS (NOMBRE,CODIGO,PRECIO_UNITARIO,ID_PROVEEDOR,PRECIO_COMPRA) VALUES ('FICHA ELECTRICA5','0255965FE',110,4,50);
SAVEPOINT lote_1;
INSERT INTO ARTICULOS (NOMBRE,CODIGO,PRECIO_UNITARIO,ID_PROVEEDOR,PRECIO_COMPRA) VALUES ('CABLE 2 PULGADAS','0255545CA',1000,1,250);
INSERT INTO ARTICULOS (NOMBRE,CODIGO,PRECIO_UNITARIO,ID_PROVEEDOR,PRECIO_COMPRA) VALUES ('CABLE 3 PULGADAS','0277545CA',1500,1,300);
INSERT INTO ARTICULOS (NOMBRE,CODIGO,PRECIO_UNITARIO,ID_PROVEEDOR,PRECIO_COMPRA) VALUES ('CABLE 4 PULGADAS','0985545CA',1600,1,350);
INSERT INTO ARTICULOS (NOMBRE,CODIGO,PRECIO_UNITARIO,ID_PROVEEDOR,PRECIO_COMPRA) VALUES ('CABLE 5 PULGADAS','0253645CA',1700,1,450);
INSERT INTO ARTICULOS (NOMBRE,CODIGO,PRECIO_UNITARIO,ID_PROVEEDOR,PRECIO_COMPRA) VALUES ('CABLE 6 PULGADAS','0255645CA',1800,1,550);
SAVEPOINT lote_2;
#CON EL SELECT A LA TABLA ARTICULOS PODEMOS VER EL INSERT MASIVO Q SE REALIZO EN LA TRANSACCION#
Select * from articulos order by id desc limit 10;
#COMANDO PARA VOLVER ATRAR EL INSERT DE DATOS DEL SAVEPOINT DEL LOTE 1#
ROLLBACK TO SAVEPOINT LOTE_1;
#COMANDO PARA BORRAR EL SAVEPOINT LOTE:2#
RELEASE SAVEPOINT LOTE_2;
#SE INICIA UNA TRANSACTION CON DOS INSERT Y UN DELETE DE LA TABLA CLIENTE#
START TRANSACTION;
INSERT INTO cliente(NOMBRE,APELLIDO,EMAIL,DNI,ACTIVO) VALUES ('Maria','DIAZ','DIAZ@GMAIL.COM',31458979,1);
INSERT INTO cliente(NOMBRE,APELLIDO,EMAIL,DNI,ACTIVO) VALUES ('MARIANO','DIAZ','DIAZ@GMAIL.COM',31478979,1);
DELETE FROM cliente WHERE ID=102;
#VOLVER ATRAR EL INSER Y EL DELETE DE LA TABLA CLIENTE#
##ROLLBACK;
#FINALIZACION DE LA TRANSACTION #
##COMMIT;
#VISUALIZACION DE LOS INSER DE LA TRANCICION INCIADA#
SELECT * FROM CLIENTE ORDER BY ID DESC LIMIT 2;